version: '3.6'
services:
  elasticsearch:
    image: elasticsearch:7.17.7
    container_name: elasticsearch
    restart: always
    volumes:
      - ./elasticsearch.yml:/usr/share/elasticsearch/elasticsearch.yml
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elk
    environment:
      ES_JAVA_OPTS: '-Xmx256m -Xms256m'
      discovery.type: single-node

  logstash:
    image: logstash:7.17.7
    container_name: logstash
    restart: always
    volumes:
      - ./logstash.yml:/usr/share/logstash/logstash.yml
      - ./pipelines.yml:/usr/share/logstash/pipelines.yml
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch
    ports:
      - 5044:5044
    environment:
      LS_JAVA_OPTS: '-Xmx256m -Xms256m'
    networks:
      - elk

  kibana:
    image: kibana:7.17.7
    container_name: kibana
    restart: always
    volumes:
      - ./kibana.yml:/usr/share/kibana/kibana.yml
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - elk

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.17.7
    container_name: filebeat
    command: filebeat -e -strict.perms=false && filebeat modules enable zeek
    restart: always
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./pcap:/pcap:ro
      - ./suricata:/suricata:ro
      # - ./zeek.yml:/usr/share/filebeat/modules.d/zeek.yml
    networks:
      - elk
    links:
      - logstash:logstash
    depends_on:
      - logstash

  zeek:
    container_name: zeek
    depends_on:
      - filebeat
    image: blacktop/zeek:elastic
    volumes:
      - ./pcap:/pcap
      - ./local.zeek:/usr/local/zeek/share/zeek/site/local.zeek
    cap_add:
      - NET_ADMIN
    network_mode: 'host'
    command: -i af_packet::ens160 local

  suricata:
    container_name: suricata
    image: jasonish/suricata:latest
    volumes:
      - ./suricata:/var/log/suricata
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_NICE
    network_mode: 'host'
    command: -i ens160

  arkime:
    container_name: arkime
    #build: ./arkime/
    image: mammo0/docker-arkime:latest
    volumes:
      - ./arkime/config:/data/config
      - ./arkime/pcap:/data/pcap
      - ./arkime/logs:/data/logs
      - ./arkime/scripts/startarkime.sh:/data/startarkime.sh:rw
    network_mode: 'host'
    #entrypoint: /bin/bash
    environment:
      - CAPTURE=on
      - OS_HOST=127.0.0.1
      - VIEWER=on
      - ARKIME_INTERFACE=ens160
      - ES_HOST=elasticsearch
      - ES_PORT=9200
networks:
  elk:
