filebeat.inputs:
  - input_type: log
    enabled: true
    paths:
      - /logs/arkime/*.log
      - /logs/suricata/suricata/*.log
      - /logs/suricata/suricata/*.json
    id: filebeat-stream
    index: 'filebeat-%{+yyyy.MM.dd}'

  - input_type: log
    enabled: true
    paths:
      - /logs/zeek/*.log
    id: zeek-stream
    index: 'zeek-%{+yyyy.MM.dd}'

  - input_type: log
    enabled: true
    paths:
      - /suricata/*.log
      - /suricata/*.json
    id: suricata-stream
    index: 'suricata-%{+yyyy.MM.dd}'

filebeat.modules:
  - module: zeek
    capture_loss:
      enabled: true
      var.paths: ['/opt/zeek/logs/current/capture_loss.json']
    connection:
      enabled: true
      var.paths: ['/opt/zeek/logs/current/conn.json']
    dce_rpc:
      enabled: true
      var.paths: ['/opt/zeek/logs/current/dce_rpc.json']
    dhcp:
      enabled: true
      var.paths: ['/opt/zeek/logs/current/dhcp.json']
    dnp3:
      enabled: true
      var.paths: ['/opt/zeek/logs/current/dnp3.json']
    dns:
      enabled: true
      var.paths: ['/opt/zeek/logs/current/dns.json']
    dpd:
      enabled: true
      var.paths: ['/opt/zeek/logs/current/dpd.json']
    files:
      enabled: true
      var.paths: ['/opt/zeek/logs/current/files.json']
    ftp:
      enabled: true
      var.paths: ['/opt/zeek/logs/current/ftp.json']
    http:
      enabled: true
      var.paths: ['/opt/zeek/logs/current/http.json']
    intel:
      enabled: true
      var.paths: ['/opt/zeek/logs/current/intel.json']
    irc:
      enabled: true
      var.paths: ['/opt/zeek/logs/current/irc.json']
    kerberos:
      enabled: true
      var.paths: ['/opt/zeek/logs/current/kerberos.json']
    modbus:
      enabled: true
      var.paths: ['/opt/zeek/logs/current/modbus.json']
    mysql:
      enabled: true
      var.paths: ['/opt/zeek/logs/current/mysql.json']
    notice:
      enabled: true
      var.paths: ['/opt/zeek/logs/current/notice.json']
    ntlm:
      enabled: true
      var.paths: ['/opt/zeek/logs/current/ntlm.json']
    ocsp:
      enabled: true
      var.paths: ['/opt/zeek/logs/current/ocsp.json']
    pe:
      enabled: true
      var.paths: ['/opt/zeek/logs/current/pe.json']
    radius:
      enabled: true
      var.paths: ['/opt/zeek/logs/current/radius.json']
    rdp:
      enabled: true
      var.paths: ['/opt/zeek/logs/current/rdp.json']
    rfb:
      enabled: true
      var.paths: ['/opt/zeek/logs/current/rfb.json']
    sip:
      enabled: true
      var.paths: ['/opt/zeek/logs/current/sip.json']
    smb_cmd:
      enabled: true
      var.paths: ['/opt/zeek/logs/current/smb_cmd.json']
    smb_files:
      enabled: true
      var.paths: ['/opt/zeek/logs/current/smb_files.json']
    smb_mapping:
      enabled: true
      var.paths: ['/opt/zeek/logs/current/smb_mapping.json']
    smtp:
      enabled: true
      var.paths: ['/opt/zeek/logs/current/smtp.json']
    snmp:
      enabled: true
      var.paths: ['/opt/zeek/logs/current/snmp.json']
    socks:
      enabled: true
      var.paths: ['/opt/zeek/logs/current/socks.json']
    ssh:
      enabled: true
      var.paths: ['/opt/zeek/logs/current/ssh.json']
    ssl:
      enabled: true
      var.paths: ['/opt/zeek/logs/current/ssl.json']
    stats:
      enabled: true
      var.paths: ['/opt/zeek/logs/current/stats.json']
    syslog:
      enabled: true
      var.paths: ['/opt/zeek/logs/current/syslog.json']
    traceroute:
      enabled: true
      var.paths: ['/opt/zeek/logs/current/traceroute.json']
    tunnel:
      enabled: true
      var.paths: ['/opt/zeek/logs/current/tunnel.json']
    weird:
      enabled: true
      var.paths: ['/opt/zeek/logs/current/weird.json']
    x509:
      enabled: true
      var.paths: ['/opt/zeek/logs/current/x509.json']

  - module: suricata
    eve:
      enabled: true
      var.paths: ['/suricata/eve.json']

setup.template:
  name: 'filebeat'
  pattern: 'filebeat-*'
  enabled: false

output.logstash:
  hosts: ['logstash:5088']
  ssl.certificate_authorities:
    - /usr/share/filebeat/config/certs/certificates/ca/ca.crt
  enabled: true
  ssl.certificate: '/usr/share/filebeat/config/certs/certificates/filebeat/filebeat.crt'
  ssl.key: '/usr/share/filebeat/config/certs/certificates/filebeat/filebeat.key'
