filebeat.inputs:
  # - input_type: log
  #   enabled: true
  #   paths:
  #     - /logs/arkime/*.log
  #     - /logs/arkime/*.json
  #     - /logs/suricata/suricata/*.log
  #     - /logs/suricata/suricata/*.json
  #   id: filebeat-stream
  #   index: 'filebeat-%{+yyyy.MM.dd}'

  # - input_type: log
  #   enabled: true
  #   paths:
  #     - /logs/zeek/*.log
  #   id: zeek-stream
  #   index: 'zeek-%{+yyyy.MM.dd}'

  # - input_type: log
  #   enabled: true
  #   paths:
  #     - /logs/suricata/*.log
  #     #- /logs/suricata/*.json
  #   id: suricata-stream
  #   index: 'suricata-%{+yyyy.MM.dd}'

filebeat.modules:
  - module: zeek
    capture_loss:
      enabled: true
      var.paths: ['/logs/zeek/capture_loss.log']
    connection:
      enabled: true
      var.paths: ['/logs/logs/zeek/conn.log']
    # dce_rpc:
    #   enabled: true
    #   var.paths: ['/logs/zeek/dce_rpc.log']
    # dhcp:
    #   enabled: true
    #   var.paths: ['/logs/zeek/dhcp.log']
    # dnp3:
    #   enabled: true
    #   var.paths: ['/logs/zeek/dnp3.log']
    # dns:
    #   enabled: true
    #   var.paths: ['/logs/zeek/dns.log']
    # dpd:
    #   enabled: true
    #   var.paths: ['/logs/zeek/dpd.log']
    # files:
    #   enabled: true
    #   var.paths: ['/logs/zeek/files.log']
    # ftp:
    #   enabled: true
    #   var.paths: ['/logs/zeek/ftp.log']
    # http:
    #   enabled: true
    #   var.paths: ['/logs/zeek/http.log']
    # intel:
    #   enabled: true
    #   var.paths: ['/logs/zeek/intel.log']
    # irc:
    #   enabled: true
    #   var.paths: ['/logs/zeek/irc.log']
    # kerberos:
    #   enabled: true
    #   var.paths: ['/logs/zeek/kerberos.log']
    # modbus:
    #   enabled: true
    #   var.paths: ['/logs/zeek/modbus.log']
    # mysql:
    #   enabled: true
    #   var.paths: ['/logs/zeek/mysql.log']
    # notice:
    #   enabled: true
    #   var.paths: ['/logs/zeek/notice.log']
    # ntlm:
    #   enabled: true
    #   var.paths: ['/logs/zeek/ntlm.log']
    # ocsp:
    #   enabled: true
    #   var.paths: ['/logs/zeek/ocsp.log']
    # pe:
    #   enabled: true
    #   var.paths: ['/logs/zeek/pe.log']
    # radius:
    #   enabled: true
    #   var.paths: ['/logs/zeek/radius.log']
    # rdp:
    #   enabled: true
    #   var.paths: ['/logs/zeek/rdp.log']
    # rfb:
    #   enabled: true
    #   var.paths: ['/logs/zeek/rfb.log']
    # sip:
    #   enabled: true
    #   var.paths: ['/logs/zeek/sip.log']
    # smb_cmd:
    #   enabled: true
    #   var.paths: ['/logs/zeek/smb_cmd.log']
    # smb_files:
    #   enabled: true
    #   var.paths: ['/logs/zeek/smb_files.log']
    # smb_mapping:
    #   enabled: true
    #   var.paths: ['/logs/zeek/smb_mapping.log']
    # smtp:
    #   enabled: true
    #   var.paths: ['/logs/zeek/smtp.log']
    # snmp:
    #   enabled: true
    #   var.paths: ['/logs/zeek/snmp.log']
    # socks:
    #   enabled: true
    #   var.paths: ['/logs/zeek/socks.log']
    # ssh:
    #   enabled: true
    #   var.paths: ['/logs/zeek/ssh.log']
    # ssl:
    #   enabled: true
    #   var.paths: ['/logs/zeek/ssl.log']
    # stats:
    #   enabled: true
    #   var.paths: ['/logs/zeek/stats.log']
    # syslog:
    #   enabled: true
    #   var.paths: ['/logs/zeek/syslog.log']
    # traceroute:
    #   enabled: true
    #   var.paths: ['/logs/zeek/traceroute.log']
    # tunnel:
    #   enabled: true
    #   var.paths: ['/logs/zeek/tunnel.log']
    # weird:
    #   enabled: true
    #   var.paths: ['/logs/zeek/weird.log']
    # x509:
    #   enabled: true
    #   var.paths: ['/logs/zeek/x509.log']

  - module: suricata
    eve:
      enabled: true
      var.paths: ['/logs/suricata/eve.json']

setup.template:
  name: 'filebeat'
  pattern: 'filebeat-*'
  enabled: false

output.logstash:
  hosts: ['logstash:5088']
  ssl.certificate_authorities:
    - /usr/share/filebeat/config/certs/certificates/ca/ca.crt
  enabled: true
  ssl.certificate: '/usr/share/filebeat/config/certs/certificates/filebeat/filebeat.crt'
  ssl.key: '/usr/share/filebeat/config/certs/certificates/filebeat/filebeat.key'
