http.host: '0.0.0.0'
http.port: 5044
xpack.monitoring.elasticsearch.hosts: ['https://elasticsearch:9200']

xpack.management.elasticsearch.username: ${ELASTICSEARCH_USER}
xpack.management.elasticsearch.password: ${ELASTICSEARCH_PASS}

xpack.monitoring.elasticsearch.username: ${ELASTICSEARCH_USER}
xpack.monitoring.elasticsearch.password: ${ELASTICSEARCH_PASS}
xpack.monitoring.elasticsearch.ssl.certificate_authority: '/usr/share/logstash/config/certs/certificates/ca/ca.crt'
